var eventList = [
	{"id": 0, "name": "Make-A-Wish Meet-up", "hostOrg": "chio", "date": "2018-11-05T12:00", "coverPhoto": "", "tags": ["sorosity", "women", "fundraiser", "greek", "service", "social"], "description": "Meet up with your fellow Chi-Os in order to celebrate Make-A-Wish!"},
	{"id": 1, "name": "Chapter Meeting", "hostOrg": "chio", "date": "2018-11-11T18:00", "coverPhoto": "", "tags": ["greek", "gbm", "sorority", "women"], "description": "Monday Meeting for Chi-Os"},
	{"id": 2, "name": "Chi-Olympics", "hostOrg": "chio", "date": "2018-11-29T14:00", "coverPhoto": "", "tags": ["greek", "service", "sorority", "women", "fundraising"], "description": "Philanthropy event put on by Chi Omega. This event is open to everyone in Greek life and those no in Greek life"},
	{"id": 3, "name": "Rush Week", "hostOrg": "sigep", "date": "2018-10-01T12:00", "coverPhoto": "", "tags": ["fraternity", "greek", "men"], "description": "Rush Week for new members of Sigma Phi Epsilon"},
	{"id": 4, "name": "Rush Week", "hostOrg": "chio", "date": "2018-10-01T12:00", "coverPhoto": "", "tags": ["sorority", "greek", "women"], "description": "Rush Week for new members of Chi Omega"},
	{"id": 5, "name": "GBM", "hostOrg": "apo", "date": "2018-12-05T18:00", "coverPhoto": "", "tags": ["gbm", "service"], "description": "GMB for Alpha Phi Omega Members"},
	{"id": 6, "name": "Fundraiser", "hostOrg": "apo", "date": "2018-12-10T15:00", "coverPhoto": "", "tags": ["fundraiser", "service"], "description": "Funraiser supporting Alpha Phi Omega. It is open to everyone and we encourage you to come!"},
	{"id": 7, "name": "Laser Tagging", "hostOrg": "apo", "date": "2018-12-12T20:00", "coverPhoto": "", "tags": ["social", "service"], "description": "Laser Tagging for all members of Alpha Phi Omega"},
	{"id": 8, "name": "Meet and Greet", "hostOrg": "apo", "date": "2018-10-10T16:00", "coverPhoto": "", "tags": ["social"], "description": "Meeting your fellow APOs and making new friends!"},
	{"id": 9, "name": "GBM", "hostOrg": "cd", "date": "2018-12-12T18:00", "coverPhoto": "", "tags": ["gbm", "pre-professional", "service"], "description": "GBM for College Democrats club and its members"},
	{"id": 10, "name": "Guest Speaker", "hostOrg": "cd", "date": "2018-12-19T18:00", "coverPhoto": "", "tags": ["pre-professional", "service"], "description": "Guest Speaker comming to a College Democrats speaking about how you can get involved with politics."},
	{"id": 11, "name": "Meet and Greet the Exec Board", "hostOrg": "cd", "date": "2018-12-20T16:00", "coverPhoto": "", "tags": ["pre-professional", "social"], "description": "Meeting the Executive Board who runs College Democrats"},
	{"id": 12, "name": "GBM", "hostOrg": "cd", "date": "2018-11-11T18:00", "coverPhoto": "", "tags": ["gbm", "pre-professional"], "description": "General Body Meeting for College Democrats"},
	{"id": 13, "name": "GBM", "hostOrg": "snap", "date": "2018-12-05T18:00", "coverPhoto": "", "tags": ["gbm", "photography", "social"], "description": "General Body Meeting for SNAP members and those intersted are more than welcome to come!"},
	{"id": 14, "name": "Hiking and Photograph", "hostOrg": "snap", "date": "2018-12-07T10:00", "coverPhoto": "", "tags": ["social", "photography"], "description": "Social event for members and non members to come learn about photography while hiking and enjoying the view!"},
	{"id": 15, "name": "Meet the Executive Board", "hostOrg": "snap", "date": "2018-12-14T15:00", "coverPhoto": "", "tags": ["photography"], "description": "Meeting the Executive Board of SNAP"},
	{"id": 16, "name": "Fundraiser", "hostOrg": "snap", "date": "2018-10-01T11:00", "coverPhoto": "", "tags": ["fundraiser", "photography"], "description": "Fundraiser selling Portos to support your local film photography club"},
	{"id": 17, "name": "GBM", "hostOrg": "ucs", "date": "2018-12-01T19:00", "coverPhoto": "", "tags": ["gbm", "pre-professional", "communication"], "description": "General Body Meeting for Undergraduate Communication Society members. Open to all, comm major or not, we welcome you!"},
	{"id": 18, "name": "Meet the Professionals", "hostOrg": "ucs", "date": "2018-12-03T11:00", "coverPhoto": "", "tags": ["pre-professional", "communication"], "description": "Meeting professions in your field!"},
	{"id": 19, "name": "Making Cookies and Friends", "hostOrg": "ucs", "date": "2018-12-12T17:00", "coverPhoto": "", "tags": ["social", "communication"], "description": "Come and socialize with members of UCS as you make new friends who may be in your communication class!"},
	{"id": 20, "name": "Meet and Greet", "hostOrg": "ucs", "date": "2018-10-10T20:00", "coverPhoto": "", "tags": ["social", "communication"], "description": "Meeting the newest members of UCS as well as introducing the Executive board to the new members!"},
	{"id": 21, "name": "GBM", "hostOrg": "vsa", "date": "2018-12-11T19:00", "coverPhoto": "", "tags": ["gbm", "asian", "community", "cultural"], "description": "General Body Meeting for VSA members"},
	{"id": 22, "name": "Social", "hostOrg": "vsa", "date": "2018-12-13T19:00", "coverPhoto": "", "tags": ["asian", "social", "community", "cultural"], "description": ""},
	{"id": 23, "name": "Bowling with your Family", "hostOrg": "vsa", "date": "2018-12-15T18:00", "coverPhoto": "", "tags": ["asian", "community", "cultural", "social"], "description": ""},
	{"id": 24, "name": "GBM", "hostOrg": "vsa", "date": "2018-11-11T17:00", "coverPhoto": "", "tags": ["asian", "cultural", "gbm", "social"], "description": ""},
	{"id": 25, "name": "Monday Meeting", "hostOrg": "aopi", "date": "2018-11-20T19:00", "coverPhoto": "", "tags": ["greek", "sorority", "women"], "description": ""},
	{"id": 26, "name": "Meeting the Alumni", "hostOrg": "aopi", "date": "2018-12-05T20:00", "coverPhoto": "", "tags": ["greek", "sorority", "social", "women"], "description": ""},
	{"id": 27, "name": "Fundraiser", "hostOrg": "aopi", "date": "2018-12-21T14:00", "coverPhoto": "", "tags": ["greek", "sorority", "social", "fundraiser", "women"], "description": ""},
	{"id": 28, "name": "GBM", "hostOrg": "aslc", "date": "2018-11-10T16:00", "coverPhoto": "", "tags": ["gbm", "cultural"], "description": ""},
	{"id": 29, "name": "Bowling", "hostOrg": "aslc", "date": "2018-11-18T15:00", "coverPhoto": "", "tags": ["cultural", "social"], "description": ""},
	{"id": 30, "name": "Meeting the Professionals", "hostOrg": "aslc", "date": "2018-12-20T12:00", "coverPhoto": "", "tags": ["cultural", "social"], "description": ""},
	{"id": 31, "name": "GBM", "hostOrg": "bsu", "date": "2018-11-15T13:00", "coverPhoto": "", "tags": ["gbm", "community", "cultural", "political"], "description": ""},
	{"id": 32, "name": "Meeting Alumni", "hostOrg": "bsu", "date": "2018-11-20T14:00", "coverPhoto": "", "tags": ["community", "cultural", "political"], "description": ""},
	{"id": 33, "name": "Social", "hostOrg": "bsu", "date": "2018-12-5T16:00", "coverPhoto": "", "tags": ["social", "community", "cultural", "political"], "description": ""},
	{"id": 34, "name": "Fundraiser", "hostOrg": "ck", "date": "2018-11-12T18:30", "coverPhoto": "", "tags": ["social", "community", "fundraiser", "service"], "description": ""},
	{"id": 35, "name": "GBM", "hostOrg": "ck", "date": "2018-11-20T16:00", "coverPhoto": "", "tags": ["gbm", "social", "community", "service"], "description": ""},
	{"id": 36, "name": "Meeting the Children", "hostOrg": "ck", "date": "2018-12-3T12:00", "coverPhoto": "", "tags": ["service", "community"], "description": ""},
	{"id": 37, "name": "Big/Little Reveal", "hostOrg": "cki", "date": "2018-11-20T14:00", "coverPhoto": "", "tags": ["community", "cultural", "service"], "description": ""},
	{"id": 38, "name": "GBM", "hostOrg": "cki", "date": "2018-11-21T11:30", "coverPhoto": "", "tags": ["gbm", "community", "service"], "description": ""},
	{"id": 39, "name": "Laser Tag & Churrios", "hostOrg": "cki", "date": "2018-12-01T13:30", "coverPhoto": "", "tags": ["social", "community"], "description": ""},
	{"id": 40, "name": "GBM", "hostOrg": "dau", "date": "2018-11-20T12:00", "coverPhoto": "", "tags": ["pre-professional", "gbm", "design"], "description": ""},
	{"id": 41, "name": "Resume Workship", "hostOrg": "dau", "date": "2018-11-29T15:00", "coverPhoto": "", "tags": ["pre-professional", "design"], "description": ""},
	{"id": 42, "name": "Fundraiser", "hostOrg": "dau", "date": "2018-12-11T09:00", "coverPhoto": "", "tags": ["fundraiser", "pre-professional", "design"], "description": ""},
	{"id": 43, "name": "Greek Meet Up", "hostOrg": "ggg", "date": "2018-11-20T08:00", "coverPhoto": "", "tags": ["greek", "social", "service", "fraternity", "sorority"], "description": ""},
	{"id": 44, "name": "Fundraiser", "hostOrg": "ggg", "date": "2018-12-13T12:00", "coverPhoto": "", "tags": ["fundraiser", "greek", "social", "service", "fraternity", "sorority"], "description": ""},
	{"id": 45, "name": "Recycling Trip", "hostOrg": "ggg", "date": "2018-12-20T13:00", "coverPhoto": "", "tags": ["service", "community", "funraiser", "greek"], "description": ""},
	{"id": 46, "name": "Family Time", "hostOrg": "kp", "date": "2018-11-11T09:00", "coverPhoto": "", "tags": ["community", "asian", "cultural", "social"], "description": ""},
	{"id": 47, "name": "GMB", "hostOrg": "kp", "date": "2018-11-12T07:00", "coverPhoto": "", "tags": ["gbm", "community", "asian", "cultural", "social"], "description": ""},
	{"id": 48, "name": "Fundraiser on Library Walk", "hostOrg": "kp", "date": "2018-12-01T12:00", "coverPhoto": "", "tags": ["funraiser", "community", "asian", "cultural", "social"], "description": ""},
	{"id": 49, "name": "GBM", "hostOrg": "nsu", "date": "2018-11-20T14:00", "coverPhoto": "", "tags": ["gbm", "cultural", "asian"], "description": ""},
	{"id": 50, "name": "Library Walk", "hostOrg": "nsu", "date": "2018-12-05T09:00", "coverPhoto": "", "tags": ["cultural", "asian"], "description": ""},
	{"id": 51, "name": "Flyering", "hostOrg": "nsu", "date": "2018-12-11T12:00", "coverPhoto": "", "tags": ["cultural", "social", "asian"], "description": ""},
	{"id": 52, "name": "GBM", "hostOrg": "piab", "date": "2018-11-10T13:00", "coverPhoto": "", "tags": ["gbm", "pre-professional", "engineering"], "description": ""},
	{"id": 53, "name": "Meeting Professionals in your Major", "hostOrg": "piab", "date": "2018-12-01T12:00", "coverPhoto": "", "tags": ["engineering", "pre-professional"], "description": ""},
	{"id": 54, "name": "Meeting Alumni", "hostOrg": "piab", "date": "2018-12-11T12:00", "coverPhoto": "", "tags": ["engineering", "pre-professional"], "description": ""},
	{"id": 55, "name": "Rush Week", "hostOrg": "tt", "date": "2018-11-20T12:00", "coverPhoto": "", "tags": ["greek", "pre-professional", "engineering"], "description": ""},
	{"id": 56, "name": "GBM", "hostOrg": "tt", "date": "2018-11-28T12:00", "coverPhoto": "", "tags": ["gbm", "engineering", "pre-professional", "men", "women"], "description": ""},
	{"id": 57, "name": "Fundraiser: Yogurt Lang", "hostOrg": "tt", "date": "2018-12-05T13:00", "coverPhoto": "", "tags": ["engineering", "fundraiser", "men", "women", "pre-professional"], "description": ""},
	{"id": 58, "name": "GBM", "hostOrg": "treo", "date": "2018-11-11T11:00", "coverPhoto": "", "tags": ["gbm", "resl-estate", "pre-professional"], "description": ""},
	{"id": 59, "name": "Meeting Professionals from LA", "hostOrg": "treo", "date": "2018-12-01T14:00", "coverPhoto": "", "tags": ["real-estate", "pre-professional"], "description": ""},
	{"id": 60, "name": "Guest Speaker", "hostOrg": "treo", "date": "2018-12-05T15:00", "coverPhoto": "", "tags": ["real-estate", "pre-professional"], "description": ""},
	{"id": 61, "name": "Alumni and Where are the Now", "hostOrg": "wib", "date": "2018-12-09T11:00", "coverPhoto": "", "tags": ["business", "pre-professional", "women"], "description": ""},
	{"id": 62, "name": "Meeting Professionals: Engineering & Business", "hostOrg": "wib", "date": "2018-12-012T12:00", "coverPhoto": "", "tags": ["business", "engineering", "pre-professional", "women"], "description": ""},
	{"id": 63, "name": "Funraiser: California Pizza Kitchen", "hostOrg": "wib", "date": "2018-12-20T09:00", "coverPhoto": "", "tags": ["business", "fundraiser", "women"], "description": ""},
	/*{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""}, */
];
