var eventList = [
	{"id": 0, "name": "Make-A-Wish Meet-up", "hostOrg": "chio", "date": "2018-11-05T12:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 1, "name": "Chapter Meeting", "hostOrg": "chio", "date": "2018-11-11T18:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 2, "name": "Chi-Olympics", "hostOrg": "chio", "date": "2018-11-29T14:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 3, "name": "Rush Week", "hostOrg": "sigep", "date": "2018-10-01T12:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 4, "name": "Rush Week", "hostOrg": "chio", "date": "2018-10-01T12:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 5, "name": "GBM", "hostOrg": "apo", "date": "2018-12-05T18:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 6, "name": "Fundraiser", "hostOrg": "apo", "date": "2018-12-10T15:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 7, "name": "Laser Tagging", "hostOrg": "apo", "date": "2018-12-12T20:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 8, "name": "Meet and Greet", "hostOrg": "apo", "date": "2018-10-10T16:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 9, "name": "GBM", "hostOrg": "cd", "date": "2018-12-12T18:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 10, "name": "Guest Speaker", "hostOrg": "cd", "date": "2018-12-19T18:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 11, "name": "Meet and Greet the Exec Board", "hostOrg": "cd", "date": "2018-12-20T16:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 12, "name": "GBM", "hostOrg": "cd", "date": "2018-11-11T18:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 13, "name": "GBM", "hostOrg": "snap", "date": "2018-12-05T18:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 14, "name": "Hiking and Photograph", "hostOrg": "snap", "date": "2018-12-07T10:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 15, "name": "Meet the Executive Board", "hostOrg": "snap", "date": "2018-12-14T15:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 16, "name": "Fundraiser", "hostOrg": "snap", "date": "2018-10-01T11:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 17, "name": "GBM", "hostOrg": "ucs", "date": "2018-12-01T19:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 18, "name": "Meet the Professionals", "hostOrg": "ucs", "date": "2018-12-03T11:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 19, "name": "Making Cookies and Friends", "hostOrg": "ucs", "date": "2018-12-12T17:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 20, "name": "Meet and Greet", "hostOrg": "ucs", "date": "2018-10-10T20:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 21, "name": "GBM", "hostOrg": "vsa", "date": "2018-12-11T19:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 22, "name": "Social", "hostOrg": "vsa", "date": "2018-12-13T19:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 23, "name": "Bowling with your Family", "hostOrg": "vsa", "date": "2018-12-15T18:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 24, "name": "GBM", "hostOrg": "vsa", "date": "2018-11-11T17:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 25, "name": "GBM", "hostOrg": "aopi", "date": "2018-11-20T19:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 26, "name": "Meeting the Alumni", "hostOrg": "aopi", "date": "2018-12-05T20:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 27, "name": "Fundraiser", "hostOrg": "aopi", "date": "2018-12-21T14:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 28, "name": "GBM", "hostOrg": "aslc", "date": "2018-11-10T16:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 29, "name": "Bowling", "hostOrg": "aslc", "date": "2018-11-18T15:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 30, "name": "Meeting the Professionals", "hostOrg": "aslc", "date": "2018-12-20T12:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 31, "name": "GBM", "hostOrg": "bsu", "date": "2018-11-15T13:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 32, "name": "Meeting Alumni", "hostOrg": "bsu", "date": "2018-11-20T14:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 33, "name": "Social", "hostOrg": "bsu", "date": "2018-12-5T16:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 34, "name": "Fundraiser", "hostOrg": "ck", "date": "2018-11-12T18:30", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 35, "name": "GBM", "hostOrg": "ck", "date": "2018-11-20T16:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 36, "name": "Meeting the Children", "hostOrg": "ck", "date": "2018-12-3T12:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 37, "name": "Big/Little Reveal", "hostOrg": "cki", "date": "2018-11-20T14:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 38, "name": "GBM", "hostOrg": "cki", "date": "2018-11-21T11:30", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 39, "name": "Laser Tag & Churrios", "hostOrg": "cki", "date": "2018-12-01T13:30", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 40, "name": "GBM", "hostOrg": "dau", "date": "2018-11-20T12:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 41, "name": "Resume Workship", "hostOrg": "dau", "date": "2018-11-29T15:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 42, "name": "Fundraiser", "hostOrg": "dau", "date": "2018-12-11T09:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 43, "name": "Greek Meet Up", "hostOrg": "ggg", "date": "2018-11-20T08:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 44, "name": "Fundraiser", "hostOrg": "ggg", "date": "2018-12-13T12:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 45, "name": "Recycling Trip", "hostOrg": "ggg", "date": "2018-12-20T13:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 46, "name": "Family Time", "hostOrg": "kp", "date": "2018-11-11T09:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 47, "name": "GMB", "hostOrg": "kp", "date": "2018-11-12T07:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 48, "name": "Fundraiser on Library Walk", "hostOrg": "kp", "date": "2018-12-01T12:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 49, "name": "GBM", "hostOrg": "nsu", "date": "2018-11-20T14:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 50, "name": "Library Walk", "hostOrg": "nsu", "date": "2018-12-05T09:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 51, "name": "Flyering", "hostOrg": "nsu", "date": "2018-12-11T12:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 52, "name": "GBM", "hostOrg": "piab", "date": "2018-11-10T13:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 53, "name": "Meeting Professionals in your Major", "hostOrg": "piab", "date": "2018-12-01T12:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 54, "name": "Meeting Alumni", "hostOrg": "piab", "date": "2018-12-11T12:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 55, "name": "Rush Week", "hostOrg": "tt", "date": "2018-11-20T12:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 56, "name": "GBM", "hostOrg": "tt", "date": "2018-11-28T12:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 57, "name": "Fundraiser: Yogurt Lang", "hostOrg": "tt", "date": "2018-12-05T13:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 58, "name": "GBM", "hostOrg": "treo", "date": "2018-11-11T11:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 59, "name": "Meeting Professionals from LA", "hostOrg": "treo", "date": "2018-12-01T14:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 60, "name": "Guest Speaker", "hostOrg": "treo", "date": "2018-12-05T15:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 61, "name": "Rush Week", "hostOrg": "ubn", "date": "2018-12-01T12:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 62, "name": "Family Reveal", "hostOrg": "ubn", "date": "2018-12-05T09:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 63, "name": "Chipotle Fundraiser", "hostOrg": "ubn", "date": "2018-12-12T11:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": , "name": "", "hostOrg": "", "date": "2018-XX-XXTXX:00", "coverPhoto": "", "tags": ["", ""], "description": ""}, */
];
