var orgList = [
	{"id": 0, "shortName": "chio", "fullName": "Chi Omega", "category": "Greek Life: Sorority", "coverPhoto": "cover1.jpg", "tags": ["greek", "sorority"], "description": "Chi Omega is a Panhellenic sorority forever committed to its founding purposes of friendship, personal integrity, service to others, academic excellence and intellectual pursuits, community and campus involvement, and personal and career development." },
	{"id": 1, "shortName": "sigep", "fullName": "Sigma Phi Epsilon", "category": "Greek Life: Fraternity", "coverPhoto": "cover2.jpg", "tags": ["", ""], "description": "Sigma Phi Epsilon, or SigEp, was founded on the three cardinal principles of Virtue, Diligence, and Brotherly Love. The men of SigEp strive to stay proactive and self-sustaining while working with their brothers to build a constantly evolving fraternity."},
	{"id": 2, "shortName": "phide", "fullName": "Phi Delta Epsilon", "category": "Pre-Professional: Medical", "coverPhoto": "cover3.jpg", "tags": ["", ""], "description": "To prepare our members for a career in medicine and to promote fraternity amongst our members."},
	{"id": 3, "shortName": "apo", "fullName": "Alpha Phi Omega", "category": "Service", "coverPhoto": "APOCover.jpg", "tags": ["", ""], "description": ""},
	{"id": 4, "shortName": "cd", "fullName": "College Democrats", "category": "Political", "coverPhoto": "CDCover.jpg", "tags": ["", ""], "description": "The purpose of the College Democrats, a non-profit organization, is to educate students about the philosophy of the Democratic Party, promote campus discussion of issues of concern to students and the nation at large, foster involvement in political movements and affect political change on a local, state and national level."},
	{"id": 5, "shortName": "snap", "fullName": "Student Network for Analog Photography", "category": "Art", "coverPhoto": "SNAPCover.jpg", "tags": ["", ""], "description": "We want to bring together students in an effort to revive the \"dying\" art that is analog photography. This organization aims to create an open platform for students to develop and build upon skills in film photography. Students will be encouraged to join, regardless of level of experience, in hopes that a network can be created for members to organize photoshoots, share work and learn about early analog technologies in photo development and camera mechanism."},
	{"id": 6, "shortName": "ucs", "fullName": "Undergraduate Communication Society", "category": "Pre-Professional: Communication", "coverPhoto": "", "tags": ["", ""], "description": "The Undergraduate Communication Society (UCS) is an organization run by and for students interested in communication. The UCS conducts career panels, field trips (in which we are not responsible for member's transportation and utilize public transportation throughout San Diego) and social events for members, often including alumni and guest speakers from the communication field."},
	{"id": 7, "shortName": "vsa", "fullName": "Vietnamese Student Association", "category": "Cultural", "coverPhoto": "VSACover.jpg", "tags": ["", ""], "description": "To promote and preserve the Vietnamese culture and awareness among the UCSD students through various cultural, social, community, and educational events."},
	/* {"id": 8, "shortName": "", "fullName": "", "category": "", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 9, "shortName": "", "fullName": "", "category": "", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 10, "shortName": "", "fullName": "", "category": "", "coverPhoto": "", "tags": ["", ""], "description": ""},
	{"id": 11, "shortName": "", "fullName": "", "category": "", "coverPhoto": "", "tags": ["", ""], "description": ""}, */
];